subRepositories:
  - url: https://github.com/svenefftinge/multi-repo-sub1
    checkoutLocation: sub-repo
tasks:
  - before: |
      cd ../sub-repo
    init: echo "hello"
workspaceLocation: multi-repo-main/my-project.code-workspace