subRepositories:
  - url: https://github.com/svenefftinge/multi-repo-sub1
tasks:
  - before: |
      cd ../multi-repo-sub1
    init: echo "hello"
workspaceLocation: multi-repo-main/my-project.code-workspace